export default [
    {
        name: "voucher_no",
        label: "Voucher No (Auto Generated)",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
        placeholder: "e.g. EV34543590",
    },
    {
        name: "expense_category",
        label: "Expense Category (খরচের ধরন)",
        type: "text",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "account_id",
        label: "Account (হিসাব)",
        type: "select",
        multiple: false,
        data_list: [],
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "amount",
        label: "Amount (পরিমাণ)",
        type: "number",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "entry_date",
        label: "Entry Date (তারিখ)",
        type: "date",
        value: "",
        is_visible: true,
        class: "col-md-6",
    },
    {
        name: "description",
        label: "Description (বিবরণ)",
        type: "textarea",
        value: "",
        is_visible: true,
        class: "col-md-12",
    },
];
