export default [
	{
		name: "user_id",
		label: "Member (সদস্য)",
		type: "select",
		multiple: false,
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "voucher_no",
		label: "Voucher No",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "amount",
		label: "Amount (পরিমাণ)",
		type: "number",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "withdrawal_date",
		label: "Withdrawal Date (তারিখ)",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "payment_method",
		label: "Payment Method",
		type: "select",
		multiple: false,
		data_list: [
			{ label: "Cash (নগদ)",      value: "cash" },
			{ label: "Bank (ব্যাংক)",   value: "bank" },
			{ label: "Mobile Banking",  value: "mobile_banking" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "reason",
		label: "Reason (কারণ)",
		type: "textarea",
		rows: 3,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "note",
		label: "Note (মন্তব্য)",
		type: "textarea",
		rows: 3,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
