export default [
  {
    name: "role_id",
    label: "Select  role ",
    type: "select",
    value: "",
    class: "col-md-6",
    data_list: [],
  },
  {
    name: "name",
    label: "user name",
    type: "text",
    value: "",
    class: "col-md-6",
  },
  {
    name: "email",
    label: "Enter email",
    type: "text",
    value: "",
    class: "col-md-6",
  },
  {
    name: "phone",
    label: "Enter phone",
    type: "text",
    value: "",
    class: "col-md-6",
  },

  {
    name: "password",
    label: "password",
    type: "text",
    value: "",
    class: "col-md-6",
  },
  {
    name: "number_of_share",
    label: "Enter number of share",
    type: "text",
    value: "",
    class: "col-md-6",
  },
  {
    name: "join_date",
    label: "Enter join date",
    type: "date",
    value: "",
    class: "col-md-6",
  },
  {
    name: "image",
    label: "image",
    type: "file",
    multiple: false,
    accept: "image/*",
    value: "",
    class: "col-md-6",
  },

  // ── Nominee Section ──
  {
    name: "nominee_name",
    label: "Nominee Name (নমিনির নাম)",
    type: "text",
    value: "",
    class: "col-md-6",
    section: "nominee",
  },
  {
    name: "nominee_relation",
    label: "Relation (সম্পর্ক)",
    type: "select",
    value: "",
    class: "col-md-6",
    section: "nominee",
    data_list: [
      { label: "Father (পিতা)",       value: "father" },
      { label: "Mother (মাতা)",       value: "mother" },
      { label: "Spouse (স্বামী/স্ত্রী)", value: "spouse" },
      { label: "Son (পুত্র)",          value: "son" },
      { label: "Daughter (কন্যা)",   value: "daughter" },
      { label: "Brother (ভাই)",       value: "brother" },
      { label: "Sister (বোন)",        value: "sister" },
      { label: "Other (অন্যান্য)",      value: "other" },
    ],
  },
  {
    name: "nominee_nid",
    label: "Nominee NID / Birth Certificate (এনআইডি / জন্মসনদ)",
    type: "text",
    value: "",
    class: "col-md-6",
    section: "nominee",
  },
  {
    name: "nominee_image",
    label: "Nominee Image (নমিনির ছবি)",
    type: "file",
    multiple: false,
    accept: "image/*",
    value: "",
    class: "col-md-6",
    section: "nominee",
  },
];
